# Generated by Django 4.1.3 on 2023-02-17 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_posted_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='posted_by',
        ),
    ]
