# Generated by Django 4.1.3 on 2023-02-20 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_dislike_count_review_like_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='dislike_count',
        ),
        migrations.RemoveField(
            model_name='review',
            name='like_count',
        ),
    ]
