# Generated by Django 4.1.3 on 2023-02-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_productlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='dislike_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='ProductLike',
        ),
    ]
