# Generated by Django 4.1.3 on 2023-02-13 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_has_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color_choice',
            field=models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('pink', 'Pink')], default='red', max_length=20),
        ),
    ]
