# Generated by Django 4.1.3 on 2023-02-20 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_dislike_count_product_dislikes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='dislike_count',
        ),
        migrations.RemoveField(
            model_name='product',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='like_count',
        ),
        migrations.RemoveField(
            model_name='product',
            name='likes',
        ),
    ]
