# Generated by Django 4.1.3 on 2023-02-13 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_color_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='has_color',
        ),
    ]
