# Generated by Django 4.1.3 on 2023-02-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_has_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_color',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='color_choice',
            field=models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('purple', 'Purple'), ('paige', 'Paige'), ('grey', 'Grey'), ('yellow', 'Yellow')], default='red', max_length=20),
        ),
    ]
